# Create a deployment for postgresql 13.1

version: '3.8'
services:
  temporal-postgres:
    image: postgres:13.1
    container_name: temporal-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: